project:
  name: Nexus
  description: Universal Development Context Management System
  version: 0.1.0

repository_structure:
  main_repo: 
    name: Nexus
    purpose: Central coordination and configuration for the entire project

  module_repositories:
    naming_convention: 
      prefix: Nexus
      examples: 
        - NexusCore
        - NexusVertex
        - NexusSynapse
        - NexusPrism
        - NexusForge

    rationale:
      - Provides clear, consistent naming
      - Enables easy identification of project modules
      - Supports scalable microservice-like architecture

directory_layout:
  root:
    - README.md: Project overview and high-level documentation
    - .nexus-context.yml: Project-wide context configuration
    - .nexus-project-structure.yml: This documentation file
    - Nexus.code-workspace: VS Code workspace configuration
    - package.json: Project-wide npm configuration

  subdirectories:
    docs:
      purpose: Detailed project documentation
    
    examples:
      purpose: Example implementations and use cases
    
    logs:
      purpose: High-level project logs and conversation histories
    
    packages:
      structure: 
        - NexusCore/
          - src/
          - logs/
        - NexusVertex/
          - src/
          - logs/
        # Similar structure for other modules
      purpose: Contain source code and logs for each module

    scripts:
      purpose: Utility and context management scripts
      key_scripts:
        - context-retriever.js

    submodules:
      purpose: Git submodules for each Nexus module
      names: 
        - Core
        - Vertex
        - Synapse
        - Prism
        - Forge

design_principles:
  - Modular architecture
  - Clear separation of concerns
  - Consistent naming conventions
  - Flexible and extensible design
  - Minimal core implementation

submodule_strategy:
  - Short directory names (Core, Vertex)
  - Full repository names (NexusCore, NexusVertex)
  - Independent but interconnected modules
  - Centralized configuration in main Nexus repository

future_considerations:
  - Potential plugin/extension ecosystem
  - Enhanced cross-editor support
  - Performance optimizations
  - Expanded context retrieval mechanisms

contact:
  maintainer: paclarap
  primary_email: 170521138+paclarap@users.noreply.github.com
